import Head from "next/head";
import axios from "axios";
import Image from "next/image";
import React, { useState, useEffect } from "react";
import moment from "moment";

export default function Home() {
  const [images, setImages] = useState(null);
  const [date, setDate] = useState(() => {
    let initialDate = new moment();
    return initialDate;
  });

  useEffect(() => {
    let formattedDate = date;
    console.log(formattedDate);
    let formattedDateClone = formattedDate.clone().format("YYYY-MM-DD");
    console.log(formattedDateClone);

    axios
      .get(
        `https://api.nasa.gov/planetary/apod?date=${formattedDateClone}&api_key=${process.env.NEXT_PUBLIC_NASA_API_KEY}`
      )
      .then(function (response) {
        setImages(response.data);
      });
  }, [date]);

  const decrementDate = () => {
    let today = date;
    let todayClone = today.clone().subtract(1, "day");
    setDate(todayClone);
  };

  if (images) {
    const imageDate = moment(images.date).format("MM-D-YYYY");
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-row h-auto w-screen gap-10 ">
        {images ? (
          <div>
            <div className="flex items-center justify-center w-full h-auto p-4 rounded-md">
              <Image
                className="rounded-md shadow-md"
                width={400}
                height={400}
                src={images.url}
              />
            </div>
            <section className="max-w-xl p-4">
              <h4 className="font-medium mr-4">
                {images.title}
                <span>
                  <button
                    className="text-lg ml-4 bg-blue-700 px-12 rounded-md"
                    onClick={decrementDate}
                  >
                    {">"}
                  </button>
                </span>
              </h4>{" "}
              <h4 className="text-gray-400 font-semibold">{imageDate}</h4>
              <p>{images.explanation}</p>
            </section>
          </div>
        ) : null}
      </main>
    </div>
  );
}
